name: Download Helm Chart

on:
  workflow_dispatch:
    inputs:
      repo:
        type: string
        required: true
        description: The target repo to download helm charts
      tag:
        type: string
        required: true
        description: A semver
      chart-name:
        type: string
        required: true
        description: The chart name

env:
  # Common versions
  PUBLISH_BRANCH: 'main'

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ env.PUBLISH_BRANCH }}
          token: ${{ secrets.PAT_TOKEN }}
      - uses: robinraju/release-downloader@v1.3
        with:
          repository: "${{ github.event.inputs.repo }}"
          tag: "v${{ github.event.inputs.tag }}"
          fileName: "${{ github.event.inputs.chart-name }}-${{ github.event.inputs.tag }}.tgz"
          out-file-path: "charts/"
          token: ${{ secrets.PAT_TOKEN }}
      - name: Push Chart
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add .
          git status
          git commit -s \
            -m "Automated upload ${{ github.event.inputs.repo }} ${{ github.event.inputs.chart-name }}-${{ github.event.inputs.tag }}.tgz"
          git push https://${{ github.token }}@github.com/${{ github.repository }}.git ${{ env.PUBLISH_BRANCH }}

